Declare M6502_log_printall in lib6502.h
This allows `make` to succeed on a vanilla Mac OS X machine, which has stopped supporting implicit function declarations by default.

```
run6502.c:409:2: error: call to undeclared function 'M6502_log_printall'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        M6502_log_printall();
        ^
```

Closes #2.